export const QUOTATION_STATUS = {
  SUBMITTED: "Submitted",
  UNDER_REVIEW: "Under Review",
  APPROVED: "Approved",
  REJECTED: "Rejected",
};

export const QUOTATION_STATUS_LIST = [
  QUOTATION_STATUS.SUBMITTED,
  QUOTATION_STATUS.UNDER_REVIEW,
  QUOTATION_STATUS.APPROVED,
  QUOTATION_STATUS.REJECTED,
];

export default QUOTATION_STATUS;
