export const REQUEST_STATUS = {
  PENDING: "Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
  PURCHASE_IN_PROGRESS: "Purchase In Progress",
  DELIVERED: "Delivered",
  COMPLETED: "Completed",
};

export const REQUEST_STATUS_LIST = [
  REQUEST_STATUS.PENDING,
  REQUEST_STATUS.APPROVED,
  REQUEST_STATUS.REJECTED,
  REQUEST_STATUS.CANCELLED,
  REQUEST_STATUS.PURCHASE_IN_PROGRESS,
  REQUEST_STATUS.DELIVERED,
  REQUEST_STATUS.COMPLETED,
];

export default REQUEST_STATUS;
